spring:
  application:
    name: skaet_assessment
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/skaet_assessment}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 2000ms

app:
  ussd:
    session-timeout: ${APP_USSD_SESSION_TIMEOUT:120}
  default:
    currency: NGN

logging:
  level:
    org.springframework.web: INFO
    com.skaet_assessment: DEBUG

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}